### ISSUE TITLE
FR: Add ability to output earliest and latest entries

### ISSUE THREAD

**Issue by benfurfie** [edalzell/statamic-history#4]
**Is your feature request related to a problem? Please describe**
I am using History to output the last time a global was updated for regulatory purposes. Currently, by default, History outputs every change. I only require the latest record.

**Describe the solution you'd like**
Two new tags, latest and earliest that will allow you to output a single record; either the earliest or the latest.

**Describe the alternatives you've considered**
Well, one of my juniors – perhaps naively – tried to put a limit modifier on the tag. Oh, that one made me chuckle.

**Additional context**
I've already done the work, including docs; it just needs checking, critiquing, and merging.

**Would you be willing to sponsor this feature?**
Even better, I've already solved it ;)

**Comment by edalzell** [comment]
added in https://github.com/edalzell/statamic-history/pull/5
